#############################################################################
# Makefile for building: candy
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 6? 26 10:44:23 2022
# Project:  candy.pro
# Template: app
# Command: /usr/lib/aarch64-linux-gnu/qt4/bin/qmake -o Makefile candy.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/opt/MVS/include -I/usr/include/opencv4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/aarch64-linux-gnu -L/opt/MVS/lib/aarch64/ -lMvCameraControl -L/usr/lib/aarch64-linux-gnu/ -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_videoio -lopencv_video -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/aarch64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		initwidget.cpp \
		passwddialog.cpp \
		camera.cpp \
		thread.cpp \
		correct.cpp \
		modifypasswdialog.cpp moc_widget.cpp \
		moc_initwidget.cpp \
		moc_passwddialog.cpp \
		moc_thread.cpp \
		moc_modifypasswdialog.cpp
OBJECTS       = main.o \
		widget.o \
		initwidget.o \
		passwddialog.o \
		camera.o \
		thread.o \
		correct.o \
		modifypasswdialog.o \
		moc_widget.o \
		moc_initwidget.o \
		moc_passwddialog.o \
		moc_thread.o \
		moc_modifypasswdialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		candy.pro
QMAKE_TARGET  = candy
DESTDIR       = 
TARGET        = candy

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h ui_initwidget.h ui_passwddialog.h ui_modifypasswdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: candy.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/aarch64-linux-gnu/libQtGui.prl \
		/usr/lib/aarch64-linux-gnu/libQtNetwork.prl \
		/usr/lib/aarch64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile candy.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/aarch64-linux-gnu/libQtGui.prl:
/usr/lib/aarch64-linux-gnu/libQtNetwork.prl:
/usr/lib/aarch64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile candy.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/candy1.0.0 || $(MKDIR) .tmp/candy1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/candy1.0.0/ && $(COPY_FILE) --parents widget.h initwidget.h passwddialog.h camera.h thread.h correct.h modifypasswdialog.h .tmp/candy1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp initwidget.cpp passwddialog.cpp camera.cpp thread.cpp correct.cpp modifypasswdialog.cpp .tmp/candy1.0.0/ && $(COPY_FILE) --parents widget.ui initwidget.ui passwddialog.ui modifypasswdialog.ui .tmp/candy1.0.0/ && (cd `dirname .tmp/candy1.0.0` && $(TAR) candy1.0.0.tar candy1.0.0 && $(COMPRESS) candy1.0.0.tar) && $(MOVE) `dirname .tmp/candy1.0.0`/candy1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/candy1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_initwidget.cpp moc_passwddialog.cpp moc_thread.cpp moc_modifypasswdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_initwidget.cpp moc_passwddialog.cpp moc_thread.cpp moc_modifypasswdialog.cpp
moc_widget.cpp: passwddialog.h \
		modifypasswdialog.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp \
		thread.h \
		camera.h \
		/opt/MVS/include/MvCameraControl.h \
		/opt/MVS/include/MvErrorDefine.h \
		/opt/MVS/include/CameraParams.h \
		/opt/MVS/include/PixelType.h \
		correct.h \
		widget.h
	/usr/lib/aarch64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_initwidget.cpp: widget.h \
		passwddialog.h \
		modifypasswdialog.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp \
		thread.h \
		camera.h \
		/opt/MVS/include/MvCameraControl.h \
		/opt/MVS/include/MvErrorDefine.h \
		/opt/MVS/include/CameraParams.h \
		/opt/MVS/include/PixelType.h \
		correct.h \
		initwidget.h
	/usr/lib/aarch64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) initwidget.h -o moc_initwidget.cpp

moc_passwddialog.cpp: passwddialog.h
	/usr/lib/aarch64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) passwddialog.h -o moc_passwddialog.cpp

moc_thread.cpp: /usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp \
		thread.h
	/usr/lib/aarch64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) thread.h -o moc_thread.cpp

moc_modifypasswdialog.cpp: modifypasswdialog.h
	/usr/lib/aarch64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) modifypasswdialog.h -o moc_modifypasswdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h ui_initwidget.h ui_passwddialog.h ui_modifypasswdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h ui_initwidget.h ui_passwddialog.h ui_modifypasswdialog.h
ui_widget.h: widget.ui
	/usr/lib/aarch64-linux-gnu/qt4/bin/uic widget.ui -o ui_widget.h

ui_initwidget.h: initwidget.ui
	/usr/lib/aarch64-linux-gnu/qt4/bin/uic initwidget.ui -o ui_initwidget.h

ui_passwddialog.h: passwddialog.ui
	/usr/lib/aarch64-linux-gnu/qt4/bin/uic passwddialog.ui -o ui_passwddialog.h

ui_modifypasswdialog.h: modifypasswdialog.ui
	/usr/lib/aarch64-linux-gnu/qt4/bin/uic modifypasswdialog.ui -o ui_modifypasswdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		passwddialog.h \
		modifypasswdialog.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp \
		thread.h \
		camera.h \
		/opt/MVS/include/MvCameraControl.h \
		/opt/MVS/include/MvErrorDefine.h \
		/opt/MVS/include/CameraParams.h \
		/opt/MVS/include/PixelType.h \
		correct.h \
		initwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		passwddialog.h \
		modifypasswdialog.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp \
		thread.h \
		camera.h \
		/opt/MVS/include/MvCameraControl.h \
		/opt/MVS/include/MvErrorDefine.h \
		/opt/MVS/include/CameraParams.h \
		/opt/MVS/include/PixelType.h \
		correct.h \
		ui_widget.h \
		/usr/include/opencv4/opencv2/imgproc/types_c.h \
		/usr/include/opencv4/opencv2/core/core_c.h \
		/usr/include/opencv4/opencv2/core/types_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

initwidget.o: initwidget.cpp initwidget.h \
		widget.h \
		passwddialog.h \
		modifypasswdialog.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp \
		thread.h \
		camera.h \
		/opt/MVS/include/MvCameraControl.h \
		/opt/MVS/include/MvErrorDefine.h \
		/opt/MVS/include/CameraParams.h \
		/opt/MVS/include/PixelType.h \
		correct.h \
		ui_initwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o initwidget.o initwidget.cpp

passwddialog.o: passwddialog.cpp passwddialog.h \
		ui_passwddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o passwddialog.o passwddialog.cpp

camera.o: camera.cpp camera.h \
		/opt/MVS/include/MvCameraControl.h \
		/opt/MVS/include/MvErrorDefine.h \
		/opt/MVS/include/CameraParams.h \
		/opt/MVS/include/PixelType.h \
		thread.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

thread.o: thread.cpp camera.h \
		/opt/MVS/include/MvCameraControl.h \
		/opt/MVS/include/MvErrorDefine.h \
		/opt/MVS/include/CameraParams.h \
		/opt/MVS/include/PixelType.h \
		thread.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread.o thread.cpp

correct.o: correct.cpp correct.h \
		/usr/include/opencv4/opencv2/opencv.hpp \
		/usr/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/include/opencv4/opencv2/core.hpp \
		/usr/include/opencv4/opencv2/core/cvdef.h \
		/usr/include/opencv4/opencv2/core/hal/interface.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/include/opencv4/opencv2/core/version.hpp \
		/usr/include/opencv4/opencv2/core/base.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/include/opencv4/opencv2/core/check.hpp \
		/usr/include/opencv4/opencv2/core/traits.hpp \
		/usr/include/opencv4/opencv2/core/matx.hpp \
		/usr/include/opencv4/opencv2/core/saturate.hpp \
		/usr/include/opencv4/opencv2/core/types.hpp \
		/usr/include/opencv4/opencv2/core/mat.hpp \
		/usr/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/include/opencv4/opencv2/core/persistence.hpp \
		/usr/include/opencv4/opencv2/core/operations.hpp \
		/usr/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/include/opencv4/opencv2/core/utility.hpp \
		/usr/include/opencv4/opencv2/core/optim.hpp \
		/usr/include/opencv4/opencv2/core/ovx.hpp \
		/usr/include/opencv4/opencv2/calib3d.hpp \
		/usr/include/opencv4/opencv2/features2d.hpp \
		/usr/include/opencv4/opencv2/flann/miniflann.hpp \
		/usr/include/opencv4/opencv2/flann/defines.h \
		/usr/include/opencv4/opencv2/flann/config.h \
		/usr/include/opencv4/opencv2/core/affine.hpp \
		/usr/include/opencv4/opencv2/dnn.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.hpp \
		/usr/include/opencv4/opencv2/core/async.hpp \
		/usr/include/opencv4/opencv2/dnn/version.hpp \
		/usr/include/opencv4/opencv2/dnn/dict.hpp \
		/usr/include/opencv4/opencv2/dnn/layer.hpp \
		/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp \
		/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp \
		/usr/include/opencv4/opencv2/flann.hpp \
		/usr/include/opencv4/opencv2/flann/flann_base.hpp \
		/usr/include/opencv4/opencv2/flann/general.h \
		/usr/include/opencv4/opencv2/flann/matrix.h \
		/usr/include/opencv4/opencv2/flann/params.h \
		/usr/include/opencv4/opencv2/flann/any.h \
		/usr/include/opencv4/opencv2/flann/saving.h \
		/usr/include/opencv4/opencv2/flann/nn_index.h \
		/usr/include/opencv4/opencv2/flann/result_set.h \
		/usr/include/opencv4/opencv2/flann/all_indices.h \
		/usr/include/opencv4/opencv2/flann/kdtree_index.h \
		/usr/include/opencv4/opencv2/flann/dynamic_bitset.h \
		/usr/include/opencv4/opencv2/flann/dist.h \
		/usr/include/opencv4/opencv2/flann/heap.h \
		/usr/include/opencv4/opencv2/flann/allocator.h \
		/usr/include/opencv4/opencv2/flann/random.h \
		/usr/include/opencv4/opencv2/flann/kdtree_single_index.h \
		/usr/include/opencv4/opencv2/flann/kmeans_index.h \
		/usr/include/opencv4/opencv2/flann/logger.h \
		/usr/include/opencv4/opencv2/flann/composite_index.h \
		/usr/include/opencv4/opencv2/flann/linear_index.h \
		/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_index.h \
		/usr/include/opencv4/opencv2/flann/lsh_table.h \
		/usr/include/opencv4/opencv2/flann/autotuned_index.h \
		/usr/include/opencv4/opencv2/flann/ground_truth.h \
		/usr/include/opencv4/opencv2/flann/index_testing.h \
		/usr/include/opencv4/opencv2/flann/timer.h \
		/usr/include/opencv4/opencv2/flann/sampling.h \
		/usr/include/opencv4/opencv2/highgui.hpp \
		/usr/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/include/opencv4/opencv2/videoio.hpp \
		/usr/include/opencv4/opencv2/imgproc.hpp \
		/usr/include/opencv4/opencv2/ml.hpp \
		/usr/include/opencv4/opencv2/ml/ml.inl.hpp \
		/usr/include/opencv4/opencv2/objdetect.hpp \
		/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/include/opencv4/opencv2/photo.hpp \
		/usr/include/opencv4/opencv2/stitching.hpp \
		/usr/include/opencv4/opencv2/stitching/warpers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp \
		/usr/include/opencv4/opencv2/core/cuda.hpp \
		/usr/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/camera.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp \
		/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp \
		/usr/include/opencv4/opencv2/video.hpp \
		/usr/include/opencv4/opencv2/video/tracking.hpp \
		/usr/include/opencv4/opencv2/video/background_segm.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o correct.o correct.cpp

modifypasswdialog.o: modifypasswdialog.cpp modifypasswdialog.h \
		ui_modifypasswdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modifypasswdialog.o modifypasswdialog.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_initwidget.o: moc_initwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_initwidget.o moc_initwidget.cpp

moc_passwddialog.o: moc_passwddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_passwddialog.o moc_passwddialog.cpp

moc_thread.o: moc_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thread.o moc_thread.cpp

moc_modifypasswdialog.o: moc_modifypasswdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modifypasswdialog.o moc_modifypasswdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

